### ISSUE TITLE
Add OSSF scorecard to repo

### ISSUE THREAD

**Issue by bendehaan** [OWASP/wrongsecrets#654]
Add an OSSF scorecard according to guidance [here](https://github.com/ossf/scorecard)

**Comment by commjoen** [comment]
We started filling it in: https://bestpractices.coreinfrastructure.org/en/projects/7024

**Comment by commjoen** [comment]
Items to discuss:

- [ ] The project MUST provide reference documentation that describes the external interface (both input and output) of the software produced by the project. [documentation_interface
- [ ] To enable collaborative review, the project's source repository MUST include interim versions for review between releases; it MUST NOT include only final releases.
- [ ] The project MUST provide, in each release, release notes that are a human-readable summary of major changes in that release to help users determine if they should upgrade and what the upgrade impact will be. The release notes MUST NOT be the raw output of a version control log (e.g., the "git log" command results are not release notes). Projects whose results are not intended for reuse in multiple locations (such as the software for a single website or service) AND employ continuous delivery MAY select "N/A". (URL required) 
- [ ] The release notes MUST identify every publicly known run-time vulnerability fixed in this release that already had a CVE assignment or similar when the release was created. This criterion may be marked as not applicable (N/A) if users typically cannot practically update the software themselves (e.g., as is often true for kernel updates). This criterion applies only to the project results, not to its dependencies. If there are no release notes or there have been no publicly known vulnerabilities, choose N/A. 
- [ ] The project MUST publish the process for reporting vulnerabilities on the project site. (URL required) [vulnerability_report_process] 
- [ ] If private vulnerability reports are supported, the project MUST include how to send the information in a way that is kept private. (URL required) [vulnerability_report_private] 
- [ ] The project's initial response time for any vulnerability report received in the last 6 months MUST be less than or equal to 14 days. [vulnerability_report_response] 
- [ ] The project MUST use at least one automated test suite that is publicly released as FLOSS (this test suite may be maintained as a separate FLOSS project). The project MUST clearly show or document how to run the test suite(s) (e.g., via a continuous integration (CI) script or via documentation in files such as BUILD.md, README.md, or CONTRIBUTING.md). [test] 
- [ ] See all of "New functionality testing"
Todo:
- [ ] Security section
- [ ] Analysis section

**Comment by AkankshaAI** [comment]
@commjoen Please assign this to me

**Comment by commjoen** [comment]
> @commjoen Please assign this to me

Hi @AkankshaAI , the "good first issue" label has been removed: this one is something to be completed by the project owners.

**Comment by commjoen** [comment]
<img width="246" alt="image" src="https://user-images.githubusercontent.com/1457214/224181721-be60754c-c302-432c-9966-0bb59ff33330.png">
we are now at 60%. i just need to evidence a few more things and we can get there...

**Comment by commjoen** [comment]
We are now at [![OpenSSF Best Practices](https://bestpractices.coreinfrastructure.org/projects/7024/badge)](https://bestpractices.coreinfrastructure.org/projects/7024) and added issues :) .

**Comment by commjoen** [comment]
Done and at passing level :) .
